### ISSUE TITLE
random crash and stacktrace

### ISSUE THREAD

**Issue by mattboll** [fyne-io/fynedesk#173]
I just had a crash and the stacktrace below

```2021/02/17 23:00:10 Fyne error:  Could not get window icon
2021/02/17 23:00:10   Cause: Neither a EWMH-style or ICCCM-style icon could be found for window id 400190 because: GetProperty: Error retrieving property '_NET_WM_ICON' on window 400190: BadWindow {NiceName: Window, Sequence: 55513, BadValue: 4194704, MinorOpcode: 0, MajorOpcode: 20} *AND* GetProperty: Error retrieving property 'WM_HINTS' on window 400190: BadWindow {NiceName: Window, Sequence: 55514, BadValue: 4194704, MinorOpcode: 0, MajorOpcode: 20}
2021/02/17 23:00:10   At: /home/mbollot/github/fynedesk/internal/x11/win/property.go:69
2021/02/17 23:00:10 Fyne error:  Could not get window icon
2021/02/17 23:00:10   Cause: Neither a EWMH-style or ICCCM-style icon could be found for window id 4000e8 because: GetProperty: Error retrieving property '_NET_WM_ICON' on window 4000e8: BadWindow {NiceName: Window, Sequence: 55526, BadValue: 4194536, MinorOpcode: 0, MajorOpcode: 20} *AND* GetProperty: Error retrieving property 'WM_HINTS' on window 4000e8: BadWindow {NiceName: Window, Sequence: 55527, BadValue: 4194536, MinorOpcode: 0, MajorOpcode: 20}
2021/02/17 23:00:10   At: /home/mbollot/github/fynedesk/internal/x11/win/property.go:69
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x7fa1280e7fff, 0xc00071bab0, 0x43c6db)
	/usr/lib/go-1.15/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/lib/go-1.15/src/runtime/debug/stack.go:16 +0x25
fyne.io/fynedesk/internal/ui.(*desktop).runFull.func1(0xc0004de000)
	/home/mbollot/github/fynedesk/internal/ui/desk_full.go:27 +0x45
panic(0x94eba0, 0xd72c50)
	/usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetCloseCallback(0x0, 0xc00583e7a0, 0x1)
	/home/mbollot/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200625191551-73d3c3675aa3/window.go:799 +0x26
fyne.io/fyne/v2/internal/driver/glfw.(*window).create.func3()
	/home/mbollot/go/pkg/mod/fyne.io/fyne/v2@v2.0.1-0.20210213200717-43d552faf186/internal/driver/glfw/window.go:1331 +0x85
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc00013a780)
	/home/mbollot/go/pkg/mod/fyne.io/fyne/v2@v2.0.1-0.20210213200717-43d552faf186/internal/driver/glfw/loop.go:97 +0x5f4
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc00013a780)
	/home/mbollot/go/pkg/mod/fyne.io/fyne/v2@v2.0.1-0.20210213200717-43d552faf186/internal/driver/glfw/driver.go:79 +0x3a
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0004e4000)
	/home/mbollot/go/pkg/mod/fyne.io/fyne/v2@v2.0.1-0.20210213200717-43d552faf186/internal/driver/glfw/window.go:449 +0x57
fyne.io/fynedesk/internal/ui.(*desktop).runFull(0xc0004de000)
	/home/mbollot/github/fynedesk/internal/ui/desk_full.go:32 +0x6e
fyne.io/fynedesk/internal/ui.(*desktop).Run(0xc0004de000)
	/home/mbollot/github/fynedesk/internal/ui/desk.go:95 +0x54
main.main()
	/home/mbollot/github/fynedesk/cmd/fynedesk/main.go:16 +0x9c
2021/02/17 23:00:10 Fyne error:  Get Protocols Error
2021/02/17 23:00:10   Cause: GetProperty: Error retrieving property 'WM_PROTOCOLS' on window 4000e8: BadWindow {NiceName: Window, Sequence: 55742, BadValue: 4194536, MinorOpcode: 0, MajorOpcode: 20}
2021/02/17 23:00:10   At: /home/mbollot/github/fynedesk/internal/x11/win/client.go:79
2021/02/17 23:00:10 Fyne error:  Close Error
2021/02/17 23:00:10   Cause: BadWindow {NiceName: Window, Sequence: 55743, BadValue: 4194536, MinorOpcode: 0, MajorOpcode: 4}
2021/02/17 23:00:10   At: /home/mbollot/github/fynedesk/internal/x11/win/client.go:92
2021/02/17 23:00:10 Fyne error:  Get Protocols Error
2021/02/17 23:00:10   Cause: GetProperty: Error retrieving property 'WM_PROTOCOLS' on window 400190: BadWindow {NiceName: Window, Sequence: 55747, BadValue: 4194704, MinorOpcode: 0, MajorOpcode: 20}
2021/02/17 23:00:10   At: /home/mbollot/github/fynedesk/internal/x11/win/client.go:79
2021/02/17 23:00:10 Fyne error:  Close Error
2021/02/17 23:00:10   Cause: BadWindow {NiceName: Window, Sequence: 55748, BadValue: 4194704, MinorOpcode: 0, MajorOpcode: 4}
2021/02/17 23:00:10   At: /home/mbollot/github/fynedesk/internal/x11/win/client.go:92
```

**Comment by andydotxyz** [comment]
Somehow a fyne window has opened but been nil.
Do you remember what you were doing at the time?

**Comment by mattboll** [comment]
I'm sorry I don't remember, sometimes when doing alt-tab I have "empty windows" that appear, but I'm not sure why or how

**Comment by mattboll** [comment]
issue is too old, not sure it will happen again
